apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-node-labeller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-node-labeller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceName:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-node-labeller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-node-labeller
subjects:
- kind: ServiceAccount
  name: kubevirt-node-labeller
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kubevirt-node-labeller
  name: kubevirt-node-labeller
spec:
  selector:
    matchLabels:
      app: kubevirt-node-labeller
  template:
    metadata:
      labels:
        app: kubevirt-node-labeller
    spec:
      serviceAccount: kubevirt-node-labeller
      containers:
      - name: kubevirt-node-labeller-sleeper
        image: quay.io/ksimon/kubevirt-node-labeller:v0.0.4
        command: ["sleep"]
        args: ["infinity"]
      initContainers:

        - image: quay.io/fromani/kvm-info-nfd-plugin:v0.1.1
          command: ["/bin/sh","-c"]
          args: ["cp /usr/bin/kvm-info-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/; cp -r /etc/kvm-info-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/conf;"]
          imagePullPolicy: Always
          name: kvm-info-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
  
        - image: quay.io/ksimon/kubevirt-cpu-nfd-plugin:0.0.2
          command: ["/bin/sh","-c"]
          args: ["cp /plugin/dest/kubevirt-cpu-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/;"]
          imagePullPolicy: Always
          name: kubevirt-cpu-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"

        - image: kubevirt/libvirt:5.0.0
          command: ["/bin/sh","-c"]
          args: ["libvirtd -d; chmod o+rw /dev/kvm; virsh domcapabilities --machine q35 --arch x86_64 --virttype kvm > /etc/kubernetes/node-feature-discovery/source.d/virsh_domcapabilities.xml;"]
          imagePullPolicy: Always
          name: libvirt
          securityContext:
            privileged: true
          resources:
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: quay.io/ksimon/kubevirt-node-labeller:v0.0.4
          name: kubevirt-node-labeller
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
            - name: host-os-release
              mountPath: "/etc/os-release"
              readOnly: true

      volumes:
        - name: nfd-source
          emptyDir: {}
        - name: host-os-release
          hostPath:
            path: "/etc/os-release"