---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-labeller
  name: node-labeller
spec:
  selector:
    matchLabels:
      app: node-labeller
  template:
    metadata:
      labels:
        app: node-labeller
    spec:
      serviceAccount: node-labeller
      containers:
      - name: node-labeller-sleeper
        image: "{{ node_labeller_registry }}/node-labeller:{{ node_labeller_version }}"
        command: ["sleep"]
        args: ["infinity"]
      initContainers:
        - image: "{{ kvm_info_registry }}/kvm-info-nfd-plugin:{{ kvm_info_version }}"
          command: ["/bin/sh","-c"]
          args: ["cp /usr/bin/kvm-caps-info-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/;"]
          imagePullPolicy: Always
          name: kvm-info-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
  
        - image: "{{ cpu_plugin_registry }}/cpu-nfd-plugin:{{ cpu_plugin_version }}"
          command: ["/bin/sh","-c"]
          args: ["cp /plugin/dest/cpu-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/; cp /config/cpu-plugin-configmap.yaml /etc/kubernetes/node-feature-discovery/source.d/cpu-plugin-configmap.yaml;"]
          imagePullPolicy: Always
          name: cpu-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
            - mountPath: /config
              name: cpu-config

        - image: "{{ virt_launcher_registry }}/virt-launcher:{{ virt_launcher_version }}"
          command: ["/bin/sh","-c"]
{% if use_kvm %}
          args: ["libvirtd -d; chmod o+rw /dev/kvm; virsh domcapabilities --machine q35 --arch x86_64 --virttype kvm > /etc/kubernetes/node-feature-discovery/source.d/virsh_domcapabilities.xml; cp -r /usr/share/libvirt/cpu_map /etc/kubernetes/node-feature-discovery/source.d/"]
{% else %}
          args: ["libvirtd -d; virsh domcapabilities --machine q35 --arch x86_64 --virttype qemu > /etc/kubernetes/node-feature-discovery/source.d/virsh_domcapabilities.xml; cp -r /usr/share/libvirt/cpu_map /etc/kubernetes/node-feature-discovery/source.d/"]
{% endif %}
          imagePullPolicy: Always
          name: libvirt
{% if use_kvm %}
          securityContext:
            privileged: true
          resources:
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
{% endif %}
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          name: node-labeller
          image: "{{ node_labeller_registry }}/node-labeller:{{ node_labeller_version }}"
{% if use_kvm %}
          securityContext:
            privileged: true
          resources:
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
{% endif %}
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"

      volumes:
        - name: nfd-source
          emptyDir: {}
        - name: cpu-config
          configMap:
            name: cpu-plugin-configmap
